export const SET_HERO = 'SET_HERO';
export const HERO_LOADING = 'HERO_LOADING';

export const SET_HEROES_PAGE = 'SET_HEROES_PAGE';
export const SET_HEROES_TOTAL = 'SET_HEROES_TOTAL';
export const HEROES_PAGE_LOADING = 'HEROES_PAGE_LOADING';
